name: myenv
channels:
  - defaults
dependencies:
  - python=3.8
  - numpy=1.22.3
  - matplotlib=3.5.1
  - pandas=1.3.3
  - scikit-learn=1.0.2
  - seaborn=0.11.2
  - pytorch=1.11.0
  - torchvision=0.12.0
  - pytorch_lightning=1.6.0
  - torchmetrics=0.8.0
  - jupyter
  - pip
  - pip:
    - imbalanced-learn==0.9.0
